"""
Django settings for mimic_backend project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# FILES_DIR = os.path.abspath(os.path.join(BASE_DIR, '../webapi'))
FILES_DIR = os.path.abspath(os.path.join(BASE_DIR, '../cqgApi'))

sys.path.insert(0, FILES_DIR)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=f@95m!at1l@aw__-&_fiu@7&v+on^8kdlyc0vi+=ubnt-c4p2'

HOST = 'local'
# HOST = 'server'

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ['100.100.7.76','localhost','127.0.0.1', 
        '100.100.7.38', '100.100.7.88', '146.148.110.243', 
        '0.0.0.0', '130.211.224.61']

DEBUG = False
MAIN_URL = 'http://130.211.224.61:8010'
WEBSITE_LINK = 'http://130.211.224.61/'
REDIRECT_LINK = 'http://130.211.224.61/#!/?email_verify=true&uid='

MIMIC_USER_NAME = 'MIMICWEBAPI'
PASSWORD = 'pass'

PEGION_LINK = 'https://api.expresspigeon.com/'
PEGION_TOKEN = '89f1c9d8-94a3-457c-a69c-dbf215631c39'

AUTH_USER_MODEL = 'api_login.User'
# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

PROJECT_APPS = [
    'api_login',
    'strategies'
]

INSTALLED_APPS = DJANGO_APPS+THIRD_PARTY_APPS+PROJECT_APPS

# AUTH_USER_MODEL = 'api_login.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

# CORS_ALLOW_METHODS = (
#     'DELETE',
#     'GET',
#     'PATCH',
#     'POST',
#     'PUT',
# )

# CORS_ORIGIN_WHITELIST = (
#     '100.100.7.38:8081'
# )

ROOT_URLCONF = 'mimic_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mimic_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'ENGINE': 'mysql.connector.django',
        'OPTIONS': {
            'autocommit': True,
            'read_default_file': os.path.join(BASE_DIR, 'base.cnf'),
            'init_command': 'SET default_storage_engine=INNODB',
            'sql_mode': 'traditional',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'flexsin.cakephpdev@gmail.com'
EMAIL_HOST_PASSWORD = 'flexsin@123'


# Media files settings

MEDIA_ROOT = os.path.join(BASE_DIR, 'images')
MEDIA_URL = '/images/'


# === CQG Credentials === #

# host_name = 'wss://demoapi.cqg.com:443'
# user_name = 'MIMICWEBAPI'
# password = 'pass'
# # user_name = 'ErHaWapi'
# # password = 'CQGD3m0P4ssw0rd'

# client_app_id = 'WebApiTest'
# client_version = 'python-client'
# timeout = 5.0
# need_to_log = False